// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YoklamaTutucu;

#nullable disable

namespace YoklamaTutucu.Migrations
{
    [DbContext(typeof(DersDtoContextAndDersdevamsizlikDtoContext))]
    [Migration("20240303153824_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YoklamaTutucu.DersDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DersAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DersOgretimGorevlisiAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("dersler");
                });

            modelBuilder.Entity("YoklamaTutucu.DersdevamsizlikDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DersId")
                        .HasColumnType("integer");

                    b.Property<int>("DevamsizlikSayisi")
                        .HasColumnType("integer");

                    b.Property<DateTime>("devamsizlikTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DersId");

                    b.ToTable("devamsizliklar");
                });

            modelBuilder.Entity("YoklamaTutucu.DersdevamsizlikDto", b =>
                {
                    b.HasOne("YoklamaTutucu.DersDto", "Ders")
                        .WithMany("DersdevamsizlikDtos")
                        .HasForeignKey("DersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");
                });

            modelBuilder.Entity("YoklamaTutucu.DersDto", b =>
                {
                    b.Navigation("DersdevamsizlikDtos");
                });
#pragma warning restore 612, 618
        }
    }
}
